export 'package:appmovie_request/views/widgets/nav_bar_widget.dart';
export 'package:appmovie_request/views/screens/home/profile_user_screen.dart';
export 'package:appmovie_request/views/screens/home/favorites_movies_screen.dart';
export 'package:appmovie_request/views/screens/home/search_movies_screen.dart';
export 'package:appmovie_request/views/screens/home/home_user_screen.dart';
export 'package:appmovie_request/views/screens/auth/register_user_screen.dart';
export 'package:appmovie_request/views/screens/auth/login_sesion_screen.dart';
export 'package:appmovie_request/views/screens/auth/init_presentation_screen.dart';
export 'package:appmovie_request/views/screens/home/select_favorites_movies_screen.dart';
